### ISSUE TITLE
Only one detail about tag name

### ISSUE THREAD

**Issue by ldariom** [bytecodealliance/wasi.dev#19]
Hello everyone, 

One comment I dont know if it's on purpose but I saw that on the [website ](https://wasi.dev/)tag we read WASI |, maybe make a confusion with WASII,
Only I comment if you want to remove | I understand can be better.

<img width="126" alt="2023-11-07 13_14_42-" src="https://github.com/bytecodealliance/wasi.dev/assets/14187352/3f329ab7-5760-4bed-aa22-5df2cb7e65aa">

<br/><br/>
Regards

**Comment by ricochet** [comment]
Fixed #23
