### ISSUE TITLE
How to use the polyfill?

### ISSUE THREAD

**Issue by joel-porquet** [bytecodealliance/wasi.dev#4]
Hi,

I'm not sure I understand how to use the demo at https://wasi.dev/polyfill/.

I downloaded the wasi sdk 5.0, and compiled a typical hello world application with it (hello.c => hello.wasm). Now I'm trying to run hello.wasm in the demo, by selecting it via the "Browse..." button but nothing happens.

Am I missing something? Isn't the demo supposed to run wasi-ready wasm program?

Thanks!

**Comment by sunfishcode** [comment]
Hello! Sorry I missed this earlier. Yes, the demo is supposed to run basic WASI programs compiled by wasi-sdk or similar, including hello world. I just tried it now, and it works for me. If it doesn't work for you, could you upload your compiled hello world program somewhere where I could look at it?

**Comment by joel-porquet** [comment]
Sorry for the delay. I was finally able to try again (same hello world with the WASI SDK 5), and it's now working. Problem solved.
