### ISSUE TITLE
No LICENSE in the repo

### ISSUE THREAD

**Issue by mh4ck-Thales** [bytecodealliance/wasi.dev#40]
There is no LICENSE file of any kind in the repository, making unclear what is the status of current and future documentation contributions. wasi.dev is a great reference for people looking into WASI, but the lack of license may block potential contributors for proposing documentation improvements and fixes, making WASI more visible and accessible for all.

**Comment by ericgregory** [comment]
Thanks for flagging this @mh4ck-Thales!
