### ISSUE TITLE
Improve tab title

### ISSUE THREAD

**Issue by rugk** [bytecodealliance/wasi.dev#8]
The current title of https://wasi.dev/ is "WASI |". IMHO, this is not very descriptive **and** it cries for something to write after the "|"…

**Comment by sunfishcode** [comment]
It's not clear why this happens. The [raw content](https://raw.githubusercontent.com/bytecodealliance/wasi.dev/gh-pages/index.md) this is generated from doesn't have the "|". If anyone can say where the "|" is coming from, it'd be greatly appreciated!

**Comment by ricochet** [comment]
Fixed #23
